defaults:
  - encoder: Omni
  - decoder: UPerNet

instance:
  _target_: models.networks.Fine_tuning.Fine
  encoder: ${model.network.encoder}
  decoder: ${model.network.decoder}
  path: ''
  output_size: ${model.network.encoder.embed_dim}
  inter_dim: []
  p_drop: 0.2
  freeze: False
  n_class: ${dataset.num_classes}
  modalities: ${modalities}
  last_block: False
  pooling_method: null
  lin_seg: False
  proj_only: False
  name: 'encoder'
