# @package _global_

defaults:
  - override /dataset: SocaPT
  - override /model/network: MAEOmni
  - override /model/network/encoder: Omni
  - override /model/train_metrics: no_metrics
  - override /model/val_metrics: metrics_contrastif
  - override /model/test_metrics: metrics_contrastif
  - override /model/loss: OmniSAT

#fast_dev_run: True
max_epochs: 10

trainer:
  num_workers: 0

dataset:
  global_batch_size: 4

model:
  name: "OmniSAT_soca_aer"
  optimizer:
    lr: 1e-4

modalities:
  - "aerial"
