# @package _global_

defaults:
  - override /dataset: SocaFT
  - override /model: SemSeg
  - override /model/network: Fine_tuning_SemSeg_uper
  - override /model/train_metrics: metrics_seg_pangaea
  - override /model/val_metrics: metrics_seg_pangaea
  - override /model/test_metrics: metrics_seg_pangaea
  - override /model/loss: CrossEntropyIgnore

#fast_dev_run: True
max_epochs: 10

trainer:
  num_workers: 0

dataset:
  global_batch_size: 4

model:
  name: "OmniSAT_soca_droneFT"
  network:
    encoder:
      return_layers: [0, 1, 3, 5]
  optimizer:
    lr: 1e-5

modalities:
  - "aerial"
  # - "s2"
  # - "s1-asc"